# Global config default values
survey_round: '2024'
convert_to_parquet: false
reload_references:
  area_name: true
  valueset: true
  validation: true
  tabulation: true
  data_dictionary: true
  macrodata: true
  score_card: true
  record: true
  section: true
working_directory: ~
check_if_online: true
complete_cases: true
read_as_chunk: false
chunk_threshold: 5000
harmonize_variable: true
input_data: hp
execute_mode: false
mode:
  type: validation
  edit: 1
  source: 2
  stage: dev
  station: co
aggregation:
  level: 5
  areas: all
validation:
  generate_output: false
  detailed_output: false
  include_additional_info: false
  validate_signatures: false
  add_uuid: true
  save_as_excel: false
  save_as_json: true
tabulation: ~
portal:
  stage: dev
  db_migration:
    overwrite: true
    append: false
version:
  app: 3.0.0
  script: 0.0.1
  package: 0.1.4
  db: 0.0.1
clear_objects: true
verbose: true
progress: false
