# Global config default values
survey_round: '2024'
read_from_parquet: no
reload_references:
  area_name: yes
  valueset: yes
  validation: yes
  tabulation: yes
  data_dictionary: yes
  macrodata: yes
  score_card: yes
  record: yes
working_directory: '.'
complete_cases: yes
chunk_threshold: 5000 # in MB
harmonize_variable: yes
input_data: hp
execute_mode: no
mode:
  type: validation
  edit: 1
  source: 2
  stage: dev
  station: co
aggregation:
  level: 1
  areas: all
validation:
  generate_output: no
  detailed_output: no
  include_additional_info: no
  validate_signatures: no
  add_uuid: yes
  save_as_excel: no
  save_as_json: yes
tabulation: ~
portal:
  stage: dev
  db_migration:
    overwrite: yes
    append: no
version:
  app: 3.0.0
  script: 0.0.1
  package: 0.1.4
  db: 0.0.1
clear_objects: yes
verbose: yes
