# Global config default values
survey_round: '2024'
parquet:
  convert: true
  encrypt: true
  overwrite: true
  partition: false
  delete_source: false
  partition_by:
    - region_code
    - province_code
    - city_mun_code
reload_references:
  area_name: true
  area_name_new: true
  valueset: true
  validation: true
  tabulation: true
  data_dictionary: true
  macrodata: true
  score_card: true
  record: true
  section: true
working_directory: ~
check_if_online: true
complete_cases: true
read_as_chunk: false
chunk_threshold: 5000
harmonize_variable: true
input_data: hp
execute_mode: false
mode:
  type: validation
  edit: 1
  source: 2
  stage: dev
  station: co
aggregation:
  level: 5
  areas: all
  by_area: false
validation:
  include_signature: false
  include_extension: false
  include_prelim: false
  generate_output: false
  detailed_output: false
  check_duplicate_members: false
  include_additional_info: false
  add_uuid: true
  save_as_excel: false
  save_as_json: true
  signature:
    ink_threshold: 375
    img_threshold: 100000
    path: ~
    valid:
      path: ~
      action: ~
    invalid:
      path: ~
      action: ~
tabulation: ~
portal:
  stage: dev
  db_migration:
    overwrite: true
    append: false
version:
  app: 3.0.0
  script: 0.0.1
  package: 0.1.4
  db: 0.0.1
clear_objects: true
verbose: true
progress: false
