cbms_round: 2022
working_directory: './playground'
read_from_parquet: no
reload_refs: yes
verbose: yes
complete_cases: yes
aggregation:
  level: 5
  areas: all
input_data: hp
mode:
  type: portal
  edit: 1
  source: 2
  stage: dev
  output:
    generate: no
    type: json
  options:
    detailed_output: no
    include_household_info: no
    add_uuid: no
    save_as_excel: no
    save_as_json: no
