cbms_round: 2022
read_from_parquet: yes
reload_references: no
working_directory: './playground'
complete_cases: yes
aggregation:
  level: 1
  areas: all
input_data: hp
mode:
  type: validation
  edit: 1
  source: 2
  stage: dev
  output:
    generate: no
    type: json
  options:
    eda: yes
    detailed_output: no
    include_household_info: no
    add_uuid: no
    save_as_excel: no
    save_as_json: no
verbose: yes
show_error_code: no
