cbms_round: 2022
working_directory: './playground'
read_from_parquet: yes
aggregation_level: 1
input_data: hp
reload_refs: no
file_format:
  hp: txt
  bp: csv
mode:
  type: validation
  source: 2
  stage: 1
  generate_output: yes
  options:
    detailed_output: no
    include_hh_info: no
    add_uuid: no
    save_as_excel: no
    save_as_json: no

2021:
  reference_period: ~
  add_length: 0
  hp:
    summary_record: summary_of_visit

2022:
  reference_period: ~
  add_length: 0
  hp:
    summary_record: summary_of_visit

2024:
  reference_period: ~
  add_length: 1
  hp:
    summary_record: cover_page
