cbms_round: 2022
working_directory: './playground'
input_file_first: summary_of_visit
read_from_parquet: yes
aggregation_level: 1
input_data: hp
reload_refs: no
file_format:
  hp: txt
  bp: csv
mode:
  type: validation
  generate_output: no
  stage: 1
  options: ~

2021:
  reference_period: ~
  add_length: 0
  hp_input_file_first: summary_of_visit

2022:
  reference_period: ~
  add_length: 0
  hp_input_file_first: summary_of_visit

2024:
  reference_period: ~
  add_length: 1
  hp_input_file_first: cover_page
